[package]
name = "tantivy"
version = "0.19.2"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[build-dependencies]
pyo3-build-config = { version = "0.19.1" }

[dependencies]
chrono = { version = "0.4.24" }
tantivy = { version = "0.19.2" }
itertools = { version = "0.10.5" }
futures = { version = "0.3.28" }
serde_json = { version = "1.0.103" }

[dependencies.pyo3]
version = "0.19.1"
features = ["extension-module"]
