name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            static.rust-lang.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: "stable"
          components: rustfmt

      - name: Check Formatting
        run: cargo fmt --check

  Test:
    continue-on-error: ${{ matrix.python-version == '3.13' }}
    env:
      UNSAFE_PYO3_SKIP_VERSION_CHECK: ${{ matrix.unsafe-pyo3-skip-version-check }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]
        allow-prereleases: [false]
        unsafe-pyo3-skip-version-check: [0]
        include:
          - os: ubuntu-latest
            python-version: "3.13"
            allow-prereleases: true
            unsafe-pyo3-skip-version-check: 1
          - os: ubuntu-latest
            python-version: "3.11"
            allow-prereleases: false
          - os: ubuntu-latest
            python-version: "3.10"
            allow-prereleases: false
          - os: ubuntu-latest
            python-version: 3.9
            allow-prereleases: false
          - os: ubuntu-latest
            python-version: 3.8
            allow-prereleases: false
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            crates.io:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            static.crates.io:443
            index.crates.io:443
            static.rust-lang.org:443
            objects.githubusercontent.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # 5.4.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: ${{ matrix.allow-prereleases }}

      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: "stable"

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0  # 2.8.0
      - run: python3 -m pip install nox
      - run: nox -s test-${{ matrix.python-version }}
      - run: cargo test
