name: Test & Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    permissions:
      contents: write  # for actions/create-release to create a release
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504 # v1
        with:
          egress-policy: audit

      - name: Get the release version from the tag
        shell: bash
        if: env.RELEASE_VERSION == ''
        run: |
          # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.RELEASE_VERSION }}"

      - name: Create GitHub release
        id: release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}

  linux:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          manylinux: auto
          command: build
          args: --release -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

      - name: Upload release binaries
        uses: alexellis/upload-assets@eaab1472d5c2f0df3115cac81136f03e7e61f771
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/tantivy-*"]'

  windows:
    runs-on: windows-latest
    needs: create-release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          command: build
          args: --release --no-sdist -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

      - name: Upload release binaries
        uses: alexellis/upload-assets@eaab1472d5c2f0df3115cac81136f03e7e61f771
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/tantivy-*"]'

  macos:
    runs-on: macos-latest
    needs: create-release
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          command: build
          args: --release --no-sdist -o dist --universal2

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

      - name: Upload release binaries
        uses: alexellis/upload-assets@eaab1472d5c2f0df3115cac81136f03e7e61f771
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./dist/tantivy-*"]'

  release-pypy:
    name: Release
    runs-on: ubuntu-latest
    needs: [ macos, windows, linux ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741  # 3.0.0
        with:
          name: wheels

      - name: Publish to PyPI Tests
        uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        with:
          command: upload
          args: --repository-url=https://test.pypi.org/legacy/ --skip-existing *

      - name: Publish to PyPI
        uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *