name: Test & Release

on:
  release:
    types: [published]

# on:
#   pull_request:
#     branches:
#       - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'x86_64-unknown-linux-gnu', 'aarch64-unknown-linux-gnu' ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            cdn.quay.io:443
            cdn01.quay.io:443
            cdn02.quay.io:443
            cdn03.quay.io:443
            crates.io:443
            files.pythonhosted.org:443
            ghcr.io:443
            github.com:443
            index.crates.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            pkg-containers.githubusercontent.com:443
            pypi.org:443
            quay.io:443
            sh.rustup.rs:443
            static.crates.io:443
            static.rust-lang.org:443

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: 3.8
          architecture: x64

      - uses: PyO3/maturin-action@bf468cfccfe9a3fec2554b0eebf2e9276cf066aa
        with:
          manylinux: auto
          target: ${{ matrix.platform }}
          command: build
          args: --release --sdist -o dist -i 3.8 3.9 3.10 3.11 3.12

      - name: Upload wheels
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b  # 4.3.4
        with:
          name: wheels-${{ matrix.platform }}
          path: dist

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10']
        target: ['universal2', 'x86_64-apple-darwin']
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels - ${{ matrix.target }}
        uses: PyO3/maturin-action@bf468cfccfe9a3fec2554b0eebf2e9276cf066aa
        env:
          PYO3_PYTHON: python${{ matrix.python-version }}
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b  # 4.3.4
        with:
          name: wheels-${{ matrix.target }}
          path: dist

  python-release-github:
    runs-on: ubuntu-latest
    needs: [ macos, linux ]
    permissions:
      contents: write # To add assets to a release.
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            uploads.github.com:443
            static.rust-lang.org:443 

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ github.head_ref }}

      - uses: dtolnay/rust-toolchain@bb45937a053e097f8591208d8e74c90db1873d07
        with:
          toolchain: 1.73.0

      - name: Set up Python 3.8
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.8

      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          path: wheels
          pattern: wheels-*
          merge-multiple: true

      - name: Upload release binaries
        uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./wheels/tantivy-*"]'
