name: Test & Release

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          manylinux: auto
          command: build
          args: --release -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

  windows:
    runs-on: windows-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          command: build
          args: --release --no-sdist -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

  macos:
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        with:
          command: build
          args: --release --no-sdist -o dist --universal2

      - name: Upload wheels
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8  # 3.1.0
        with:
          name: wheels
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ macos, windows, linux ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741  # 3.0.0
        with:
          name: wheels

      - name: Publish to PyPI Tests
        uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        with:
          command: upload
          args: --repository-url=https://test.pypi.org/legacy/ --skip-existing *

      - name: Publish to PyPI
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: messense/maturin-action@20111a7c286a91434bdd7f612314a38ff6c091ad
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *